//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalkulator.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zespolone", Namespace="http://schemas.datacontract.org/2004/07/UslugiSieciowe")]
    [System.SerializableAttribute()]
    public partial class Zespolone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double I {
            get {
                return this.IField;
            }
            set {
                if ((this.IField.Equals(value) != true)) {
                    this.IField = value;
                    this.RaisePropertyChanged("I");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double R {
            get {
                return this.RField;
            }
            set {
                if ((this.RField.Equals(value) != true)) {
                    this.RField = value;
                    this.RaisePropertyChanged("R");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AboutException", Namespace="http://schemas.datacontract.org/2004/07/UslugiSieciowe")]
    [System.SerializableAttribute()]
    public partial class AboutException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ZDodaj", ReplyAction="http://tempuri.org/IService1/ZDodajResponse")]
        Kalkulator.ServiceReference.Zespolone ZDodaj(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ZDodaj", ReplyAction="http://tempuri.org/IService1/ZDodajResponse")]
        System.IAsyncResult BeginZDodaj(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, System.AsyncCallback callback, object asyncState);
        
        Kalkulator.ServiceReference.Zespolone EndZDodaj(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ZMinus", ReplyAction="http://tempuri.org/IService1/ZMinusResponse")]
        Kalkulator.ServiceReference.Zespolone ZMinus(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ZMinus", ReplyAction="http://tempuri.org/IService1/ZMinusResponse")]
        System.IAsyncResult BeginZMinus(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, System.AsyncCallback callback, object asyncState);
        
        Kalkulator.ServiceReference.Zespolone EndZMinus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ZMnoz", ReplyAction="http://tempuri.org/IService1/ZMnozResponse")]
        Kalkulator.ServiceReference.Zespolone ZMnoz(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ZMnoz", ReplyAction="http://tempuri.org/IService1/ZMnozResponse")]
        System.IAsyncResult BeginZMnoz(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, System.AsyncCallback callback, object asyncState);
        
        Kalkulator.ServiceReference.Zespolone EndZMnoz(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ZDziel", ReplyAction="http://tempuri.org/IService1/ZDzielResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Kalkulator.ServiceReference.AboutException), Action="http://tempuri.org/IService1/ZDzielAboutExceptionFault", Name="AboutException", Namespace="http://schemas.datacontract.org/2004/07/UslugiSieciowe")]
        Kalkulator.ServiceReference.Zespolone ZDziel(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ZDziel", ReplyAction="http://tempuri.org/IService1/ZDzielResponse")]
        System.IAsyncResult BeginZDziel(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, System.AsyncCallback callback, object asyncState);
        
        Kalkulator.ServiceReference.Zespolone EndZDziel(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Kalkulator.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZDodajCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ZDodajCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Kalkulator.ServiceReference.Zespolone Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Kalkulator.ServiceReference.Zespolone)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZMinusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ZMinusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Kalkulator.ServiceReference.Zespolone Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Kalkulator.ServiceReference.Zespolone)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZMnozCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ZMnozCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Kalkulator.ServiceReference.Zespolone Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Kalkulator.ServiceReference.Zespolone)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZDzielCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ZDzielCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Kalkulator.ServiceReference.Zespolone Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Kalkulator.ServiceReference.Zespolone)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Kalkulator.ServiceReference.IService1>, Kalkulator.ServiceReference.IService1 {
        
        private BeginOperationDelegate onBeginZDodajDelegate;
        
        private EndOperationDelegate onEndZDodajDelegate;
        
        private System.Threading.SendOrPostCallback onZDodajCompletedDelegate;
        
        private BeginOperationDelegate onBeginZMinusDelegate;
        
        private EndOperationDelegate onEndZMinusDelegate;
        
        private System.Threading.SendOrPostCallback onZMinusCompletedDelegate;
        
        private BeginOperationDelegate onBeginZMnozDelegate;
        
        private EndOperationDelegate onEndZMnozDelegate;
        
        private System.Threading.SendOrPostCallback onZMnozCompletedDelegate;
        
        private BeginOperationDelegate onBeginZDzielDelegate;
        
        private EndOperationDelegate onEndZDzielDelegate;
        
        private System.Threading.SendOrPostCallback onZDzielCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ZDodajCompletedEventArgs> ZDodajCompleted;
        
        public event System.EventHandler<ZMinusCompletedEventArgs> ZMinusCompleted;
        
        public event System.EventHandler<ZMnozCompletedEventArgs> ZMnozCompleted;
        
        public event System.EventHandler<ZDzielCompletedEventArgs> ZDzielCompleted;
        
        public Kalkulator.ServiceReference.Zespolone ZDodaj(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2) {
            return base.Channel.ZDodaj(z1, z2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginZDodaj(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginZDodaj(z1, z2, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Kalkulator.ServiceReference.Zespolone EndZDodaj(System.IAsyncResult result) {
            return base.Channel.EndZDodaj(result);
        }
        
        private System.IAsyncResult OnBeginZDodaj(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Kalkulator.ServiceReference.Zespolone z1 = ((Kalkulator.ServiceReference.Zespolone)(inValues[0]));
            Kalkulator.ServiceReference.Zespolone z2 = ((Kalkulator.ServiceReference.Zespolone)(inValues[1]));
            return this.BeginZDodaj(z1, z2, callback, asyncState);
        }
        
        private object[] OnEndZDodaj(System.IAsyncResult result) {
            Kalkulator.ServiceReference.Zespolone retVal = this.EndZDodaj(result);
            return new object[] {
                    retVal};
        }
        
        private void OnZDodajCompleted(object state) {
            if ((this.ZDodajCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ZDodajCompleted(this, new ZDodajCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ZDodajAsync(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2) {
            this.ZDodajAsync(z1, z2, null);
        }
        
        public void ZDodajAsync(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, object userState) {
            if ((this.onBeginZDodajDelegate == null)) {
                this.onBeginZDodajDelegate = new BeginOperationDelegate(this.OnBeginZDodaj);
            }
            if ((this.onEndZDodajDelegate == null)) {
                this.onEndZDodajDelegate = new EndOperationDelegate(this.OnEndZDodaj);
            }
            if ((this.onZDodajCompletedDelegate == null)) {
                this.onZDodajCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnZDodajCompleted);
            }
            base.InvokeAsync(this.onBeginZDodajDelegate, new object[] {
                        z1,
                        z2}, this.onEndZDodajDelegate, this.onZDodajCompletedDelegate, userState);
        }
        
        public Kalkulator.ServiceReference.Zespolone ZMinus(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2) {
            return base.Channel.ZMinus(z1, z2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginZMinus(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginZMinus(z1, z2, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Kalkulator.ServiceReference.Zespolone EndZMinus(System.IAsyncResult result) {
            return base.Channel.EndZMinus(result);
        }
        
        private System.IAsyncResult OnBeginZMinus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Kalkulator.ServiceReference.Zespolone z1 = ((Kalkulator.ServiceReference.Zespolone)(inValues[0]));
            Kalkulator.ServiceReference.Zespolone z2 = ((Kalkulator.ServiceReference.Zespolone)(inValues[1]));
            return this.BeginZMinus(z1, z2, callback, asyncState);
        }
        
        private object[] OnEndZMinus(System.IAsyncResult result) {
            Kalkulator.ServiceReference.Zespolone retVal = this.EndZMinus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnZMinusCompleted(object state) {
            if ((this.ZMinusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ZMinusCompleted(this, new ZMinusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ZMinusAsync(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2) {
            this.ZMinusAsync(z1, z2, null);
        }
        
        public void ZMinusAsync(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, object userState) {
            if ((this.onBeginZMinusDelegate == null)) {
                this.onBeginZMinusDelegate = new BeginOperationDelegate(this.OnBeginZMinus);
            }
            if ((this.onEndZMinusDelegate == null)) {
                this.onEndZMinusDelegate = new EndOperationDelegate(this.OnEndZMinus);
            }
            if ((this.onZMinusCompletedDelegate == null)) {
                this.onZMinusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnZMinusCompleted);
            }
            base.InvokeAsync(this.onBeginZMinusDelegate, new object[] {
                        z1,
                        z2}, this.onEndZMinusDelegate, this.onZMinusCompletedDelegate, userState);
        }
        
        public Kalkulator.ServiceReference.Zespolone ZMnoz(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2) {
            return base.Channel.ZMnoz(z1, z2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginZMnoz(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginZMnoz(z1, z2, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Kalkulator.ServiceReference.Zespolone EndZMnoz(System.IAsyncResult result) {
            return base.Channel.EndZMnoz(result);
        }
        
        private System.IAsyncResult OnBeginZMnoz(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Kalkulator.ServiceReference.Zespolone z1 = ((Kalkulator.ServiceReference.Zespolone)(inValues[0]));
            Kalkulator.ServiceReference.Zespolone z2 = ((Kalkulator.ServiceReference.Zespolone)(inValues[1]));
            return this.BeginZMnoz(z1, z2, callback, asyncState);
        }
        
        private object[] OnEndZMnoz(System.IAsyncResult result) {
            Kalkulator.ServiceReference.Zespolone retVal = this.EndZMnoz(result);
            return new object[] {
                    retVal};
        }
        
        private void OnZMnozCompleted(object state) {
            if ((this.ZMnozCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ZMnozCompleted(this, new ZMnozCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ZMnozAsync(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2) {
            this.ZMnozAsync(z1, z2, null);
        }
        
        public void ZMnozAsync(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, object userState) {
            if ((this.onBeginZMnozDelegate == null)) {
                this.onBeginZMnozDelegate = new BeginOperationDelegate(this.OnBeginZMnoz);
            }
            if ((this.onEndZMnozDelegate == null)) {
                this.onEndZMnozDelegate = new EndOperationDelegate(this.OnEndZMnoz);
            }
            if ((this.onZMnozCompletedDelegate == null)) {
                this.onZMnozCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnZMnozCompleted);
            }
            base.InvokeAsync(this.onBeginZMnozDelegate, new object[] {
                        z1,
                        z2}, this.onEndZMnozDelegate, this.onZMnozCompletedDelegate, userState);
        }
        
        public Kalkulator.ServiceReference.Zespolone ZDziel(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2) {
            return base.Channel.ZDziel(z1, z2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginZDziel(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginZDziel(z1, z2, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Kalkulator.ServiceReference.Zespolone EndZDziel(System.IAsyncResult result) {
            return base.Channel.EndZDziel(result);
        }
        
        private System.IAsyncResult OnBeginZDziel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Kalkulator.ServiceReference.Zespolone z1 = ((Kalkulator.ServiceReference.Zespolone)(inValues[0]));
            Kalkulator.ServiceReference.Zespolone z2 = ((Kalkulator.ServiceReference.Zespolone)(inValues[1]));
            return this.BeginZDziel(z1, z2, callback, asyncState);
        }
        
        private object[] OnEndZDziel(System.IAsyncResult result) {
            Kalkulator.ServiceReference.Zespolone retVal = this.EndZDziel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnZDzielCompleted(object state) {
            if ((this.ZDzielCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ZDzielCompleted(this, new ZDzielCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ZDzielAsync(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2) {
            this.ZDzielAsync(z1, z2, null);
        }
        
        public void ZDzielAsync(Kalkulator.ServiceReference.Zespolone z1, Kalkulator.ServiceReference.Zespolone z2, object userState) {
            if ((this.onBeginZDzielDelegate == null)) {
                this.onBeginZDzielDelegate = new BeginOperationDelegate(this.OnBeginZDziel);
            }
            if ((this.onEndZDzielDelegate == null)) {
                this.onEndZDzielDelegate = new EndOperationDelegate(this.OnEndZDziel);
            }
            if ((this.onZDzielCompletedDelegate == null)) {
                this.onZDzielCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnZDzielCompleted);
            }
            base.InvokeAsync(this.onBeginZDzielDelegate, new object[] {
                        z1,
                        z2}, this.onEndZDzielDelegate, this.onZDzielCompletedDelegate, userState);
        }
    }
}
